const $=s=>document.querySelector(s),video=$('#video'),stage=$('#stage'),roi=$('#roi'),valueEl=$('#value'),statusEl=$('#status'),threshold=$('#threshold'),thresholdOut=$('#thresholdOut'),polarity=$('#polarity'),confirmRange=$('#confirm'),confirmOut=$('#confirmOut'),digitWidth=$('#digitWidth'),digitWidthOut=$('#digitWidthOut'),soundCheck=$('#sound'),vibrateCheck=$('#vibrate'),debug=$('#debug'),dctx=debug.getContext('2d',{willReadFrequently:true}),work=document.createElement('canvas'),wctx=work.getContext('2d',{willReadFrequently:true});
let stream,timer,zeroCount=0,notified=false,audioCtx,startedAt=0,lastRaw='',stableFrames=0;
const WARMUP=2500,STABLE=4,SEG={'1111110':'0','0110000':'1','1101101':'2','1111001':'3','0110011':'4','1011011':'5','1011111':'6','1110000':'7','1111111':'8','1111011':'9'},BOX=[[.24,.08,.52,.14],[.69,.16,.16,.31],[.69,.55,.16,.31],[.24,.79,.52,.14],[.15,.55,.16,.31],[.15,.16,.16,.31],[.24,.44,.52,.14]];
function save(){localStorage.setItem('sevenSegSettings',JSON.stringify({threshold:threshold.value,polarity:polarity.value,confirm:confirmRange.value,digitWidth:digitWidth.value,sound:soundCheck.checked,vibrate:vibrateCheck.checked,roi:{left:roi.style.left,top:roi.style.top,width:roi.style.width,height:roi.style.height}}))}
function load(){try{const s=JSON.parse(localStorage.getItem('sevenSegSettings')||'{}');if(s.threshold)threshold.value=s.threshold;if(s.polarity)polarity.value=s.polarity;if(s.confirm)confirmRange.value=s.confirm;if(s.digitWidth)digitWidth.value=s.digitWidth;if(typeof s.sound==='boolean')soundCheck.checked=s.sound;if(typeof s.vibrate==='boolean')vibrateCheck.checked=s.vibrate;if(s.roi)Object.assign(roi.style,s.roi)}catch{} thresholdOut.value=threshold.value;confirmOut.value=confirmRange.value;digitWidthOut.value=digitWidth.value+'%'}
async function startCamera(){try{statusEl.textContent='カメラ起動中…';stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});video.srcObject=stream;await new Promise(r=>video.readyState>=1?r():video.addEventListener('loadedmetadata',r,{once:true}));await video.play();stage.style.aspectRatio=`${video.videoWidth}/${video.videoHeight}`;$('#start').disabled=true;$('#stop').disabled=false;startedAt=performance.now();lastRaw='';stableFrames=zeroCount=0;valueEl.textContent='---';statusEl.textContent='映像を安定化中…';timer=setInterval(analyze,220)}catch(e){statusEl.textContent='カメラを開始できません';alert('カメラ権限を確認してください。\n'+e.message)}}
function stopCamera(){clearInterval(timer);stream?.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;stage.style.aspectRatio='';$('#start').disabled=false;$('#stop').disabled=true;statusEl.textContent='停止中';valueEl.textContent='---';zeroCount=stableFrames=0;lastRaw=''}
function analyze(){if(!stream||!video.videoWidth)return;if(performance.now()-startedAt<WARMUP){statusEl.textContent='映像を安定化中…';return}const sr=stage.getBoundingClientRect(),rr=roi.getBoundingClientRect(),xs=video.videoWidth/sr.width,ys=video.videoHeight/sr.height,sx=Math.max(0,(rr.left-sr.left)*xs),sy=Math.max(0,(rr.top-sr.top)*ys),fullSw=Math.min(video.videoWidth-sx,rr.width*xs),sh=Math.min(video.videoHeight-sy,rr.height*ys),sw=fullSw*(+digitWidth.value/100);if(sw<30||sh<20)return;work.width=Math.round(sw);work.height=Math.round(sh);wctx.drawImage(video,sx,sy,sw,sh,0,0,work.width,work.height);const img=wctx.getImageData(0,0,work.width,work.height),gray=new Uint8Array(work.width*work.height);for(let i=0,p=0;i<img.data.length;i+=4,p++)gray[p]=Math.round(img.data[i]*.299+img.data[i+1]*.587+img.data[i+2]*.114);const chars=[];debug.width=480;debug.height=180;dctx.drawImage(work,0,0,480,180);for(let d=0;d<3;d++){const x0=Math.floor(work.width*d/3),x1=Math.floor(work.width*(d+1)/3),dw=x1-x0,bits=[];for(const [rx,ry,rw,rh] of BOX){const bx=Math.floor(x0+rx*dw),by=Math.floor(ry*work.height),bw=Math.max(1,Math.floor(rw*dw)),bh=Math.max(1,Math.floor(rh*work.height));let on=0,total=0;for(let y=by;y<Math.min(work.height,by+bh);y+=2)for(let x=bx;x<Math.min(work.width,bx+bw);x+=2){const g=gray[y*work.width+x],active=polarity.value==='bright'?g>=+threshold.value:g<=+threshold.value;if(active)on++;total++}const ratio=total?on/total:0;bits.push(ratio>.42?'1':'0')}chars.push(SEG[bits.join('')]??'?')}const raw=chars.join('');stableFrames=raw===lastRaw&&!raw.includes('?')?stableFrames+1:raw.includes('?')?0:1;lastRaw=raw;if(raw.includes('?')){valueEl.textContent='---';statusEl.textContent='数字を認識できません';zeroCount=0;return}valueEl.textContent=raw;if(stableFrames<STABLE){statusEl.textContent=`確認中 ${stableFrames}/${STABLE}`;return}handleValue(raw)}
function handleValue(v){if(v==='000'){zeroCount++;statusEl.textContent=`000確認中 ${zeroCount}/${confirmRange.value}`}else{zeroCount=0;statusEl.textContent='監視中';notified=false}if(zeroCount>=+confirmRange.value&&!notified){notified=true;statusEl.textContent='000を検出しました';fireAlert()}}
function beep(){audioCtx||=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=880;g.gain.value=.08;o.connect(g);g.connect(audioCtx.destination);o.start();setTimeout(()=>o.stop(),900)}
async function fireAlert(){if(soundCheck.checked)beep();if(vibrateCheck.checked&&navigator.vibrate)navigator.vibrate([250,120,250,120,600]);if('Notification'in window&&Notification.permission==='granted'){try{const reg=await navigator.serviceWorker?.ready;if(reg)reg.showNotification('000を検出しました',{body:'3桁表示が000になりました。',tag:'seven-seg-zero'})}catch{}}}
async function requestNotification(){if(!('Notification'in window))return alert('このブラウザは通知に対応していません。');const p=await Notification.requestPermission();alert(p==='granted'?'通知を許可しました。':'通知は許可されませんでした。')}
let action=null;roi.addEventListener('pointerdown',e=>{e.preventDefault();roi.setPointerCapture(e.pointerId);const r=roi.getBoundingClientRect(),s=stage.getBoundingClientRect();action={h:e.target.classList.contains('h'),c:e.target.className,x:e.clientX,y:e.clientY,l:r.left-s.left,t:r.top-s.top,w:r.width,hh:r.height,sw:s.width,sh:s.height}});roi.addEventListener('pointermove',e=>{if(!action)return;let l=action.l,t=action.t,w=action.w,h=action.hh,dx=e.clientX-action.x,dy=e.clientY-action.y;if(!action.h){l+=dx;t+=dy}else{const c=action.c;if(c.includes('r'))w+=dx;if(c.includes('l')){l+=dx;w-=dx}if(c.includes('b'))h+=dy;if(c.includes('t')){t+=dy;h-=dy}}w=Math.max(120,Math.min(w,action.sw-l));h=Math.max(55,Math.min(h,action.sh-t));l=Math.max(0,Math.min(l,action.sw-w));t=Math.max(0,Math.min(t,action.sh-h));roi.style.left=l/action.sw*100+'%';roi.style.top=t/action.sh*100+'%';roi.style.width=w/action.sw*100+'%';roi.style.height=h/action.sh*100+'%'});roi.addEventListener('pointerup',()=>{action=null;save()});
$('#start').onclick=startCamera;$('#stop').onclick=stopCamera;$('#notify').onclick=requestNotification;[threshold,polarity,confirmRange,digitWidth,soundCheck,vibrateCheck].forEach(el=>el.addEventListener('input',()=>{thresholdOut.value=threshold.value;confirmOut.value=confirmRange.value;digitWidthOut.value=digitWidth.value+'%';save()}));load();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
