const $=s=>document.querySelector(s);
const video=$('#video'),stage=$('#stage'),roi=$('#roi'),valueEl=$('#value'),statusEl=$('#status');
const polarity=$('#polarity'),confirmRange=$('#confirm'),confirmOut=$('#confirmOut');
const soundCheck=$('#sound'),vibrateCheck=$('#vibrate'),flashCheck=$('#flash'),flashTest=$('#flashTest'),flashStatus=$('#flashStatus');
const debug=$('#debug'),dctx=debug.getContext('2d',{willReadFrequently:true});
const base=document.createElement('canvas'),bctx=base.getContext('2d',{willReadFrequently:true});
const grayCanvas=document.createElement('canvas'),gctx=grayCanvas.getContext('2d',{willReadFrequently:true});
const binCanvas=document.createElement('canvas'),binCtx=binCanvas.getContext('2d',{willReadFrequently:true});
const invCanvas=document.createElement('canvas'),invCtx=invCanvas.getContext('2d',{willReadFrequently:true});
let stream=null,videoTrack=null,running=false,torchSupported=false,torchBusy=false,audioCtx=null;
let worker=null,ocrReady=false,ocrBusy=false,lastOcrAt=0,recent=[],zeroHits=0,nonZeroHits=0,notified=false;
const OCR_MS=520;

function save(){localStorage.setItem('ocrSettingsV7',JSON.stringify({polarity:polarity.value,confirm:confirmRange.value,sound:soundCheck.checked,vibrate:vibrateCheck.checked,flash:flashCheck.checked,roi:{left:roi.style.left,top:roi.style.top,width:roi.style.width,height:roi.style.height}}))}
function load(){try{const s=JSON.parse(localStorage.getItem('ocrSettingsV7')||localStorage.getItem('ocrSettingsV6')||'{}');if(s.polarity)polarity.value=s.polarity;if(s.confirm)confirmRange.value=s.confirm;if(typeof s.sound==='boolean')soundCheck.checked=s.sound;if(typeof s.vibrate==='boolean')vibrateCheck.checked=s.vibrate;if(typeof s.flash==='boolean')flashCheck.checked=s.flash;if(s.roi)Object.assign(roi.style,s.roi)}catch{}confirmOut.value=confirmRange.value}

function loadTesseract(){if(window.Tesseract)return initTesseract();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.async=true;s.onload=initTesseract;s.onerror=()=>{statusEl.textContent='OCRの読み込みに失敗しました'};document.head.appendChild(s)}
async function initTesseract(){if(worker||!window.Tesseract)return;try{statusEl.textContent='OCR準備中…';worker=await Tesseract.createWorker('eng',1,{logger:()=>{}});await worker.setParameters({tessedit_char_whitelist:'0123456789',tessedit_pageseg_mode:'7',preserve_interword_spaces:'0',classify_bln_numeric_mode:'1'});ocrReady=true;if(running)statusEl.textContent='監視中（精度優先）'}catch(e){console.warn(e);statusEl.textContent='OCRの初期化に失敗しました'}}

function updateTorchSupport(){videoTrack=stream?.getVideoTracks?.()[0]||null;torchSupported=false;try{torchSupported=!!videoTrack?.getCapabilities?.().torch}catch{}flashTest.disabled=!torchSupported;flashStatus.textContent=torchSupported?'フラッシュ対応：利用できます。':'このカメラ/ブラウザではフラッシュ制御を利用できません。'}
async function setTorch(on){if(!torchSupported||!videoTrack)return false;try{await videoTrack.applyConstraints({advanced:[{torch:!!on}]});return true}catch(e){console.warn('torch',e);return false}}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function flashPattern(force=false){if((!force&&!flashCheck.checked)||!torchSupported||torchBusy)return;torchBusy=true;try{for(const [on,ms] of [[true,180],[false,120],[true,180],[false,120],[true,350],[false,0]]){if(!running)break;await setTorch(on);if(ms)await wait(ms)}}finally{await setTorch(false);torchBusy=false}}

async function startCamera(){try{statusEl.textContent='カメラ起動中…';stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:2560},height:{ideal:1440}},audio:false});video.srcObject=stream;await new Promise(r=>video.readyState>=1?r():video.addEventListener('loadedmetadata',r,{once:true}));await video.play();stage.style.aspectRatio=`${video.videoWidth}/${video.videoHeight}`;updateTorchSupport();$('#start').disabled=true;$('#stop').disabled=false;running=true;recent=[];zeroHits=nonZeroHits=0;notified=false;valueEl.textContent='---';statusEl.textContent=ocrReady?'監視中（精度優先）':'OCR準備中…';schedule();if(!ocrReady&&!worker)loadTesseract()}catch(e){statusEl.textContent='カメラを開始できません';alert('カメラ権限を確認してください。\n'+e.message)}}
async function stopCamera(){running=false;try{await setTorch(false)}catch{}stream?.getTracks().forEach(t=>t.stop());stream=null;videoTrack=null;torchSupported=false;video.srcObject=null;stage.style.aspectRatio='';flashTest.disabled=true;flashStatus.textContent='カメラ開始後にフラッシュ対応状況を確認します。';$('#start').disabled=false;$('#stop').disabled=true;statusEl.textContent='停止中';valueEl.textContent='---';recent=[];zeroHits=nonZeroHits=0}
function schedule(){if(!running)return;requestAnimationFrame(()=>{if(!running)return;runOcr();schedule()})}

function percentile(hist,total,q){let target=total*q,n=0;for(let i=0;i<256;i++){n+=hist[i];if(n>=target)return i}return 255}
function otsu(hist,total){let sum=0;for(let i=0;i<256;i++)sum+=i*hist[i];let sumB=0,wB=0,best=0,max=0;for(let i=0;i<256;i++){wB+=hist[i];if(!wB)continue;const wF=total-wB;if(!wF)break;sumB+=i*hist[i];const mB=sumB/wB,mF=(sum-sumB)/wF,v=wB*wF*(mB-mF)*(mB-mF);if(v>max){max=v;best=i}}return best}
function cropBase(){const sr=stage.getBoundingClientRect(),rr=roi.getBoundingClientRect(),xs=video.videoWidth/sr.width,ys=video.videoHeight/sr.height;const sx=Math.max(0,(rr.left-sr.left)*xs),sy=Math.max(0,(rr.top-sr.top)*ys),sw=Math.min(video.videoWidth-sx,rr.width*xs),sh=Math.min(video.videoHeight-sy,rr.height*ys);if(sw<40||sh<25)return false;const H=360,W=Math.max(480,Math.min(1400,Math.round(H*sw/sh))),padX=Math.round(W*.08),padY=Math.round(H*.14);base.width=W+padX*2;base.height=H+padY*2;bctx.fillStyle='#fff';bctx.fillRect(0,0,base.width,base.height);bctx.imageSmoothingEnabled=true;bctx.imageSmoothingQuality='high';bctx.drawImage(video,sx,sy,sw,sh,padX,padY,W,H);return true}
function buildVariants(){const W=base.width,H=base.height,src=bctx.getImageData(0,0,W,H),d=src.data,hist=new Uint32Array(256),gray=new Uint8Array(W*H);let total=0;for(let i=0,p=0;i<d.length;i+=4,p++){const g=Math.round(d[i]*.299+d[i+1]*.587+d[i+2]*.114);gray[p]=g;hist[g]++;total++}const lo=percentile(hist,total,.03),hi=percentile(hist,total,.97),range=Math.max(12,hi-lo),t=otsu(hist,total);let darkMode=polarity.value==='dark';if(polarity.value==='auto'){let edge=0,center=0,ne=0,nc=0;for(let y=Math.floor(H*.15);y<H*.85;y+=5)for(let x=0;x<W;x+=5){const g=gray[y*W+x];if(x<W*.12||x>W*.88){edge+=g;ne++}else{center+=g;nc++}}darkMode=(center/nc)<(edge/ne)}
for(const c of [grayCanvas,binCanvas,invCanvas]){c.width=W;c.height=H}
const gi=gctx.createImageData(W,H),bi=binCtx.createImageData(W,H),ii=invCtx.createImageData(W,H);for(let p=0;p<gray.length;p++){let gv=Math.round((gray[p]-lo)*255/range);gv=Math.max(0,Math.min(255,gv));const ink=darkMode?gray[p]<t:gray[p]>t;const bv=ink?0:255,iv=255-bv,idx=p*4;gi.data[idx]=gi.data[idx+1]=gi.data[idx+2]=gv;gi.data[idx+3]=255;bi.data[idx]=bi.data[idx+1]=bi.data[idx+2]=bv;bi.data[idx+3]=255;ii.data[idx]=ii.data[idx+1]=ii.data[idx+2]=iv;ii.data[idx+3]=255}gctx.putImageData(gi,0,0);binCtx.putImageData(bi,0,0);invCtx.putImageData(ii,0,0);debug.width=480;debug.height=Math.round(480*H/W);dctx.drawImage(binCanvas,0,0,debug.width,debug.height)}
function cleanResult(data){const raw=(data.text||'').replace(/\D/g,'').slice(0,4);return{raw,conf:Math.max(0,Math.min(1,(data.confidence||0)/100))}}
async function recognizeOne(canvas){const{data}=await worker.recognize(canvas);return cleanResult(data)}

async function runOcr(){if(!running||!ocrReady||ocrBusy||!video.videoWidth||performance.now()-lastOcrAt<OCR_MS)return;lastOcrAt=performance.now();if(!cropBase())return;buildVariants();ocrBusy=true;statusEl.textContent='高精度OCR中…';try{const results=[];for(const c of [grayCanvas,binCanvas,invCanvas]){const r=await recognizeOne(c);if(r.raw.length>=1&&r.raw.length<=4)results.push(r)}if(!results.length){statusEl.textContent='数字を認識中…';return}const grouped=new Map();for(const r of results){const g=grouped.get(r.raw)||{score:0,count:0,best:0};g.score+=.35+r.conf;g.count++;g.best=Math.max(g.best,r.conf);grouped.set(r.raw,g)}const ranked=[...grouped.entries()].sort((a,b)=>(b[1].count-a[1].count)||(b[1].score-a[1].score));const [raw,g]=ranked[0];const conf=Math.min(1,(g.score/Math.max(1,g.count))*(g.count>=2?1.08:.82));updateTemporal(raw,conf,g.count)}catch(e){console.warn('OCR',e);statusEl.textContent='OCRエラー'}finally{ocrBusy=false}}

function updateTemporal(raw,conf,agree){const now=performance.now();recent.push({raw,conf,t:now,agree});recent=recent.filter(x=>now-x.t<1800).slice(-6);const votes=new Map();for(const r of recent){const g=votes.get(r.raw)||{score:0,count:0,best:0};g.score+=(r.agree>=2?.6:.25)+r.conf;g.count++;g.best=Math.max(g.best,r.conf);votes.set(r.raw,g)}const ranked=[...votes.entries()].sort((a,b)=>(b[1].score-a[1].score));if(!ranked.length)return;const [chosen,g]=ranked[0];const second=ranked[1]?.[1]?.score||0;const strong=(g.count>=2&&g.score-second>=.45)||(agree>=2&&conf>=.62)||(conf>=.86);if(!strong){statusEl.textContent=`確認中… ${raw} ${Math.round(conf*100)}%`;return}valueEl.textContent=chosen;handleValue(chosen,Math.min(1,g.best))}
function handleValue(v,conf){if(/^0{1,4}$/.test(v)){nonZeroHits=0;zeroHits++;statusEl.textContent=`0確認 ${zeroHits}/${confirmRange.value}`;if(zeroHits>=+confirmRange.value&&!notified){notified=true;statusEl.textContent='0を検出しました';fireAlert()}}else{zeroHits=0;nonZeroHits++;if(nonZeroHits>=2)notified=false;statusEl.textContent=`監視中（精度優先） ${Math.round(conf*100)}%`}}

function beep(){audioCtx||=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=880;g.gain.value=.08;o.connect(g);g.connect(audioCtx.destination);o.start();setTimeout(()=>o.stop(),900)}
async function fireAlert(){if(soundCheck.checked)beep();if(vibrateCheck.checked&&navigator.vibrate)navigator.vibrate([250,120,250,120,600]);flashPattern();if('Notification'in window&&Notification.permission==='granted'){try{const reg=await navigator.serviceWorker?.ready;if(reg)reg.showNotification('0を検出しました',{body:'指定した表示が0になりました。',tag:'ocr-zero'})}catch{}}}
async function requestNotification(){if(!('Notification'in window))return alert('このブラウザは通知に対応していません。');const p=await Notification.requestPermission();alert(p==='granted'?'通知を許可しました。':'通知は許可されませんでした。')}

let action=null;roi.addEventListener('pointerdown',e=>{e.preventDefault();roi.setPointerCapture(e.pointerId);const r=roi.getBoundingClientRect(),s=stage.getBoundingClientRect();action={h:e.target.classList.contains('h'),c:e.target.className,x:e.clientX,y:e.clientY,l:r.left-s.left,t:r.top-s.top,w:r.width,hh:r.height,sw:s.width,sh:s.height}});roi.addEventListener('pointermove',e=>{if(!action)return;let l=action.l,t=action.t,w=action.w,h=action.hh,dx=e.clientX-action.x,dy=e.clientY-action.y;if(!action.h){l+=dx;t+=dy}else{const c=action.c;if(c.includes('r'))w+=dx;if(c.includes('l')){l+=dx;w-=dx}if(c.includes('b'))h+=dy;if(c.includes('t')){t+=dy;h-=dy}}w=Math.max(90,Math.min(w,action.sw-l));h=Math.max(45,Math.min(h,action.sh-t));l=Math.max(0,Math.min(l,action.sw-w));t=Math.max(0,Math.min(t,action.sh-h));roi.style.left=l/action.sw*100+'%';roi.style.top=t/action.sh*100+'%';roi.style.width=w/action.sw*100+'%';roi.style.height=h/action.sh*100+'%'});roi.addEventListener('pointerup',()=>{action=null;recent=[];save()});roi.addEventListener('pointercancel',()=>action=null);

$('#start').onclick=startCamera;$('#stop').onclick=stopCamera;$('#notify').onclick=requestNotification;flashTest.onclick=()=>flashPattern(true);[polarity,confirmRange,soundCheck,vibrateCheck,flashCheck].forEach(el=>el.addEventListener('input',()=>{confirmOut.value=confirmRange.value;recent=[];save()}));
load();loadTesseract();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
